package com.morallenplay.dropthemeat.registry;

import net.minecraft.world.food.FoodProperties;

public class FoodRegistry {
	public static final FoodProperties  RAW_ALLAY = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_ARMADILLO = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_AXOLOTL = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties  RAW_BAT = (new FoodProperties.Builder().nutrition(1).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_BEAR = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties  RAW_BEE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_CAMEL = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties  RAW_CAT = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties  RAW_DOLPHIN = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties  RAW_FOX = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties  RAW_FROG = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties  RAW_GOAT = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties  RAW_HORSE = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties  RAW_LLAMA = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).build());
	public static final FoodProperties  RAW_PARROT = (new FoodProperties.Builder().nutrition(1).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_SNIFFER = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_SQUID = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.45F).build());
	public static final FoodProperties  RAW_TURTLE = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.1F).build());
	public static final FoodProperties  RAW_VILLAGER = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_WOLF = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.3F).build());
	public static final FoodProperties  RAW_STRIDER = (new FoodProperties.Builder().nutrition(3).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_IRON_GOLEM = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.75F).build());
	public static final FoodProperties  FROZEN_GOLEM_NUGGET = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.3F).build());
	public static final FoodProperties  PIGLIN_PORKCHOP = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.75F).build());
	public static final FoodProperties  VILLAGER_NOSE = (new FoodProperties.Builder().nutrition(9).saturationModifier(0.7F).build());
	public static final FoodProperties  COOKED_ALLAY = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.5F).build());
	public static final FoodProperties  COOKED_ARMADILLO = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.4F).build());
	public static final FoodProperties  COOKED_AXOLOTL = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.3F).build());
	public static final FoodProperties  COOKED_BAT = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.6F).build());
	public static final FoodProperties  COOKED_BEAR = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.8F).build());
	public static final FoodProperties  COOKED_BEE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.5F).build());
	public static final FoodProperties  COOKED_CAMEL = (new FoodProperties.Builder().nutrition(7).saturationModifier(0.7F).build());
	public static final FoodProperties  COOKED_CAT = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.4F).build());
	public static final FoodProperties  COOKED_DOLPHIN = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.8F).build());
	public static final FoodProperties  COOKED_FOX = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.4F).build());
	public static final FoodProperties  COOKED_FROG = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.8F).build());
	public static final FoodProperties  COOKED_GOAT = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.8F).build());
	public static final FoodProperties  COOKED_HORSE = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.8F).build());
	public static final FoodProperties  COOKED_LLAMA = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.8F).build());
	public static final FoodProperties  COOKED_PARROT = (new FoodProperties.Builder().nutrition(4).saturationModifier(0.7F).build());
	public static final FoodProperties  COOKED_SNIFFER = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.5F).build());
	public static final FoodProperties  COOKED_SQUID = (new FoodProperties.Builder().nutrition(7).saturationModifier(0.7F).build());
	public static final FoodProperties  COOKED_TURTLE = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.5F).build());
	public static final FoodProperties  COOKED_VILLAGER = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.4F).build());
	public static final FoodProperties  COOKED_WOLF = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.4F).build());
	public static final FoodProperties  COOKED_STRIDER = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.4F).build());
	public static final FoodProperties  COOKED_GOLEM_NUGGET = (new FoodProperties.Builder().nutrition(5).saturationModifier(1.2F).build());
	public static final FoodProperties  COOKED_IRON_GOLEM = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.85F).build());
	public static final FoodProperties  COOKED_PIGLIN_PORKCHOP = (new FoodProperties.Builder().nutrition(8).saturationModifier(0.85F).build());
	public static final FoodProperties  RAW_RED_MEAT = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.3F).build());
	public static final FoodProperties  RAW_WHITE_MEAT = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.2F).build());
	public static final FoodProperties  RAW_MONSTER_MEAT = (new FoodProperties.Builder().nutrition(2).saturationModifier(0.3F).build());
	public static final FoodProperties  COOKED_RED_MEAT = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.6F).build());
	public static final FoodProperties  COOKED_WHITE_MEAT = (new FoodProperties.Builder().nutrition(5).saturationModifier(0.6F).build());
	public static final FoodProperties  COOKED_MONSTER_MEAT = (new FoodProperties.Builder().nutrition(6).saturationModifier(0.6F).build());
}
